#include <bits/stdc++.h>
using namespace std;

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    int t;
    cin >> t;
    while (t--) {
     int n;
    cin >> n;
    vector<int> a(n);
	for (int i = 0; i < n; ++i)
		cin >> a[i];
    bool x=false;
	for (int i = 1; i < n - 1; ++i) {
		if (a[i] > a[i - 1] && a[i] > a[i + 1]) {
			cout << "YES" << endl;
			cout << i << ' ' << i + 1 << ' ' << i + 2 << endl;
            x=true;
            break;
		}
	}
	if(!x)cout << "NO" << endl;  
    }
    return 0;
}